### PR TITLE
French Translation

### PR DESCRIPTION
**Pull request by Nylux**
If anything's missing or incorrect / broken, let me know I'll try to fix it ASAP !
(I'm still learning translating mods / using github)

### CODE REVIEW

**Comment by SandyTheGreat** [comment]
Thx very much.. i cant find errors since i dont know french.. i'll just update the mod and let users give feedback..

**Comment by Nylux** [comment]
I meant if i somehow broke your code or something ^^
I'd be glad to hear it and to adjust if need be :)

**Comment by SandyTheGreat** [comment]
Thx.. so far, i see no errors in the xml.. first time seeing the LanguageInfo file.. what does it do? it wont break anything, right? lol

**Comment by Nylux** [comment]
Haha no it should be fine !
It's made to show the translator's name afaik.
It's probably (most likely) useless so if you feel like it you can remove it I won't mind at all x)

**Comment by SandyTheGreat** [comment]
Nah, its ok.. since its not gonna break anything.. i also credited u.. Thx man.. Happy Holidays..

**Comment by Nylux** [comment]
Thanks you very much I appreciate it !
Merry Christmas to you and enjoy your holidays as well ;)

**Pull request merged**
